packages:
  - core
  - observability
  - rpc
  - lakehouse
  - writer
  - reader
  - query
  - edge-cache
  - lance-reader
  - snippets-chain
  - snippets-lance
  - benchmark
  - codegen
  - e2e
  - test-utils
  - graphql
  - react
