export { Type, Encoding, WalOp, MAGIC, VERSION, HEADER_SIZE, FOOTER_SIZE, type Column, type EncodedColumn, type ColumnStats, type BlockHeader, type BlockOptions, type WalEntry, type Schema, type SchemaColumn, type StorageAdapter, type BlockId, type SnapshotId, type BatchId, type WalId, type SchemaId, type TableId, blockId, snapshotId, batchId, walId, schemaId, tableId, unsafeBlockId, unsafeSnapshotId, unsafeBatchId, unsafeWalId, unsafeSchemaId, unsafeTableId, isValidBlockId, isValidSnapshotId, isValidBatchId, isValidWalId, isValidSchemaId, isValidTableId, assertNever, } from './types.js';
export { shred, unshred, extractPath, extractPaths, coerceToType, appendRows, buildPathIndex, } from './shred.js';
export { encode, decode, unpackBits, encodeDict, encodeDelta, fastDecodeInt32, fastDecodeFloat64, fastDecodeDeltaInt32, iterateNonNullIndices, batchDecode, type FastDecodeOptions, } from './encode.js';
export { LRUStringPool, internString, getStringPoolStats, resetStringPool, type StringPoolStats, } from './string-intern-pool.js';
export { writeBlock, readBlock, getBlockStats } from './block.js';
export { createWalEntry, serializeWalEntry, deserializeWalEntry, batchWalEntries, unbatchWalEntries, getWalRange, } from './wal.js';
export { inferSchema, serializeSchema, deserializeSchema, isCompatible, migrateColumns, schemaDiff, type SchemaDiff, } from './schema.js';
export { createDOAdapter, createDOKVAdapter, createMemoryAdapter, makeBlockId, parseBlockId, makeWalId, parseWalId, type ObjectStorageAdapter, type ObjectMetadata, type R2BucketLike, type R2ObjectLike, type R2ObjectsLike, type R2PutOptionsLike, type R2ListOptionsLike, R2ObjectStorageAdapter, MemoryObjectStorageAdapter, createR2ObjectAdapter, createMemoryObjectAdapter, wrapStorageBackend, } from './storage.js';
export { shouldMerge, selectBlocksForMerge, mergeBlocks, createMergeScheduler, getMergeStats, type MergeConfig, type MergeState, } from './merge.js';
export { type PartitionMode, type AccountTier, type PartitionModeConfig, type PartitionCalculation, type PartitionPathInfo, type ModeSelectionResult, DO_SQLITE_MAX_BYTES, STANDARD_MAX_BYTES, ENTERPRISE_MAX_BYTES, DO_SQLITE_BLOCK_SIZE, STANDARD_BLOCK_SIZE, ENTERPRISE_BLOCK_SIZE, DO_SQLITE_CONFIG, STANDARD_CONFIG, ENTERPRISE_CONFIG, PARTITION_MODE_CONFIGS, getPartitionModeConfig, calculatePartitions, getPartitionPath, getAllPartitionPaths, parsePartitionPath, selectPartitionMode, formatBytes, fitsInSinglePartition, getRecommendedBlockSize, validateModeForDataSize, calculatePartitionBoundaries, estimateDataSize, getModeByMaxSize, } from './partition-modes.js';
export { type FilterOperator, type FilterPredicate, type SortDirection, type SortSpec, type AggregateFunction, type AggregateSpec, type FilterEvaluator, type AggregationEngine, type ResultProcessor, evaluateFilter, evaluateFilters, createFilterEvaluator, sortRows, limitRows, compareForSort, compareValues, createResultProcessor, computeAggregate, computeAggregations, createAggregationEngine, getNestedValue, setNestedValue, likePatternToRegex, queryOps, } from './query-ops.js';
export { SNIPPET_MAGIC, SNIPPET_VERSION, CHUNK_SIZE, SNIPPET_HEADER_SIZE, ZONE_MAP_SIZE, COLUMN_DIR_ENTRY_SIZE, BLOOM_BITS_PER_ELEMENT, BLOOM_HASH_COUNT, MAX_DICT_SIZE, BIT_WIDTHS, SnippetEncoding, type SnippetHeader, type ColumnDirEntry, type ZoneMap, type SnippetColumn, type DecodeOptions, type DecodedColumn, computeBitWidth, bitPack, bitUnpack, deltaEncode, deltaDecode, BloomFilter, computeZoneMap, canSkipByZoneMap, buildSortedDict, dictBinarySearch, encodeSortedDict, decodeSortedDict, encodeSnippetColumn, decodeSnippetColumn, packBitmap, unpackBitmap, zeroCopyDecodeInt32, zeroCopyDecodeFloat64, writeSnippetChunk, readSnippetHeader, readSnippetChunk, } from './snippet-format.js';
//# sourceMappingURL=index.d.ts.map